# Generated by Django 5.2 on 2025-08-21 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0006_alter_athleteinfo_weight'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='Сделай 10 Забегов!', max_length=32)),
                ('athlete', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='athlete_challenge', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
