# Generated by Django 5.2 on 2025-09-12 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0014_alter_collectibleitem_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='run_time_seconds',
            field=models.IntegerField(null=True),
        ),
    ]
