# Generated by Django 5.2 on 2025-10-12 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0017_subscribe'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscribe',
            name='rating',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
